# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  filter_sets:
    squared_thumbnail_medium:
      quality: 100
      filters:
        thumbnail:
          size: [300, 300]
          mode: outbound
          allow_upscale: true

    squared_thumbnail_small:
      filters:
        thumbnail:
          size: [200, 200]
          mode: outbound
          allow_upscale: true

    squared_thumbnail_big:
      filters:
        thumbnail:
          size: [800, 800]
          mode: outbound
          allow_upscale: true

    squared_thumbnail_min:
      filters:
        thumbnail:
          size: [100, 100]
          mode: outbound
          allow_upscale: true

    squared_thumbnail_annonce_view:
      filters:
        thumbnail:
          size: [900, 900]
          mode: outbound
          allow_upscale: true

    squared_thumbnail_brand:
      filters:
        thumbnail:
          size: [600, 400]
          mode: outbound
          allow_upscale: true

    squared_thumbnail_profil:
      filters:
        thumbnail:
          size: [320, 100]
          mode: outbound
          allow_upscale: true

    squared_thumbnail_user:
      filters:
        thumbnail:
          size: [200, 50]
          mode: outbound
          allow_upscale: true
